In [1]:
import numpy as np

In [26]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [27]:
X.shape

(4, 3)

In [28]:
weights = np.array([[0.513], [0.221], [0.635]])

In [29]:
weights.shape

(3, 1)

In [30]:
preds = np.matmul(X, weights)

In [31]:
preds.shape

(4, 1)

In [32]:
preds

array([[ 2.86 ],
       [ 6.967],
       [11.074],
       [15.181]])

In [34]:
np.round(preds, 2)

array([[ 2.86],
       [ 6.97],
       [11.07],
       [15.18]])

In [35]:
ground_truth = np.array([ [1], [6], [12], [15]])

In [37]:
error_squared = np.square(preds - ground_truth)

In [42]:
error_squared

array([[3.4596  ],
       [0.935089],
       [0.857476],
       [0.032761]])

In [38]:
error = np.mean(error_squared)

In [39]:
error

1.3212315000000001

In [41]:
np.round(error, 5)

1.32123

In [43]:
import numpy as np
from numpy.typing import NDArray


# Helpful functions:
# https://numpy.org/doc/stable/reference/generated/numpy.matmul.html
# https://numpy.org/doc/stable/reference/generated/numpy.mean.html
# https://numpy.org/doc/stable/reference/generated/numpy.square.html

class Solution:
    
    def get_model_prediction(self, X: NDArray[np.float64], weights: NDArray[np.float64]) -> NDArray[np.float64]:
        # X is an Nx3 NumPy array
        # weights is a 3x1 NumPy array
        # HINT: np.matmul() will be useful
        # return np.round(your_answer, 5)
        preds = np.matmul(X, weights)
        return np.round(preds, 5)


    def get_error(self, model_prediction: NDArray[np.float64], ground_truth: NDArray[np.float64]) -> float:
        # model_prediction is an Nx1 NumPy array
        # ground_truth is an Nx1 NumPy array
        # HINT: np.mean(), np.square() will be useful
        # return round(your_answer, 5)
        error_squared = np.square(model_prediction - ground_truth)
        error = np.mean(error_squared)
        return np.round(error, 5)

In [44]:
class Solution:
    def get_derivative(self, model_prediction: NDArray[np.float64], ground_truth: NDArray[np.float64], N: int, X: NDArray[np.float64], desired_weight: int) -> float:
        # note that N is just len(X)
        return -2 * np.dot(ground_truth - model_prediction, X[:, desired_weight]) / N

    def get_model_prediction(self, X: NDArray[np.float64], weights: NDArray[np.float64]) -> NDArray[np.float64]:
        return np.squeeze(np.matmul(X, weights))

    learning_rate = 0.01

    def train_model(
        self, 
        X: NDArray[np.float64], 
        Y: NDArray[np.float64], 
        num_iterations: int, 
        initial_weights: NDArray[np.float64]
    ) -> NDArray[np.float64]:

        # you will need to call get_derivative() for each weight
        # and update each one separately based on the learning rate!
        # return np.round(your_answer, 5)
        for num_iter in range(num_iterations):
            # w = w - l.r*w_derivative
            preds = self.get_model_prediction(X, initial_weights)
            for w_idx, w in enumerate(initial_weights):
                derivative_w = self.get_derivative(preds, Y, len(X), X, w_idx)
                initial_weights[w_idx] = w - Solution.learning_rate*derivative_w

        return np.round(initial_weights,  5)